/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

import java.util.ArrayList;
import java.util.List;

public class Aviao {
    private int maxTripulantes;
    private int maxPassageiros;
    private float maxCombustivel;
    private List<Motor> motores;

    public Aviao(int maxTripulantes, int maxPassageiros, float maxCombustivel) {
        this.maxTripulantes = maxTripulantes;
        this.maxPassageiros = maxPassageiros;
        this.maxCombustivel = maxCombustivel;
        this.motores = new ArrayList<>();
    }

    public void ligar() {
        for (Motor motor : motores) {
            motor.ligar();
        }
    }

    public void desligar() {
        for (Motor motor : motores) {
            motor.desligar();
        }
    }

    public void adicionarMotor(Motor motor) {
        if (motores.size() < 8) {
            motores.add(motor);
        } else {
            System.out.println("Limite máximo de 8 motores atingido.");
        }
    }


    public int getMaxTripulantes() {
        return maxTripulantes;
    }

    public void setMaxTripulantes(int maxTripulantes) {
        this.maxTripulantes = maxTripulantes;
    }

    public int getMaxPassageiros() {
        return maxPassageiros;
    }

    public void setMaxPassageiros(int maxPassageiros) {
        this.maxPassageiros = maxPassageiros;
    }

    public float getMaxCombustivel() {
        return maxCombustivel;
    }

    public void setMaxCombustivel(float maxCombustivel) {
        this.maxCombustivel = maxCombustivel;
    }

    public List<Motor> getMotores() {
        return motores;
    }
}